version: "3"
services:
  mongodb_server:
    image: "mongo"
    ports:
      - "27017:27017"
  travel_plan_service:
    build: .
    ports:
      - "8082:8082"
    environment:
      - MONGO_CONNECTION_URL=mongodb://mongodb_server:27017/travel_plan_service
